name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.AUTH_TOKEN }}

            - name: Extract tag name
              if: ${{ github.event_name != 'workflow_dispatch' }}
              id: get_tag
              run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: ghcr.io/${{ github.repository }}
                  tags: |
                      type=raw,value=test,enable=${{ github.event_name == 'workflow_dispatch' }}
                      type=ref,event=tag,enable=${{ github.event_name != 'workflow_dispatch' }}
                      type=raw,value=latest,enable=${{ github.event_name != 'workflow_dispatch' }}
            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
